### ISSUE TITLE
Twillio WhatsApp Adapter Microsoft botframework

### ISSUE THREAD

**Issue by nboussarsaracn** [BotBuilderCommunity/botbuilder-community-js#171]
I cannot seem to find the problem with linking a microsoft bot to whatsapp via Twilio.

I have followed instructions to setup the [Twilio WhatsApp adapter](https://www.npmjs.com/package/@botbuildercommunity/adapter-twilio-whatsapp).

I have implemented this on the standard echo bot for testing

```javascript
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

const dotenv = require('dotenv');
const path = require('path');
const restify = require('restify');

// This bot's main dialog.
const { TwilioWhatsAppAdapter } = require('@botbuildercommunity/adapter-twilio-whatsapp');

// Import required bot services.
// See https://aka.ms/bot-services to learn more about the different parts of a bot.
const { BotFrameworkAdapter } = require('botbuilder');

// This bot's main dialog.
const { EchoBot } = require('./bot');

// Import required bot configuration.
const ENV_FILE = path.join(__dirname, '.env');
dotenv.config({ path: ENV_FILE });
// Create HTTP server
const server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3978, () => {
    console.log(`\n${ server.name } listening to ${ server.url }`);
    console.log('\nGet Bot Framework Emulator: https://aka.ms/botframework-emulator');
    console.log('\nTo talk to your bot, open the emulator select "Open Bot"');
});

// Create adapter.
// See https://aka.ms/about-bot-adapter to learn more about how bots work.
const adapter = new BotFrameworkAdapter({
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword,
    channelService: process.env.ChannelService,
    openIdMetadata: process.env.BotOpenIdMetadata
});

const adapterSettings = {
    appId: process.env.MicrosoftAppId,
    appPassword: process.env.MicrosoftAppPassword
};

const twilioWhatsAppAdapterSettings = {
    accountSid: process.env.TWILIO_ACCOUNT_SID, // Account SID
    authToken: process.env.TWILIO_AUTH_TOKEN, // Auth Token
    phoneNumber: process.env.TWILIO_NUMBER, // The From parameter consisting of whatsapp: followed by the sending WhatsApp number (using E.164 formatting)
    endpointUrl: process.env.TWILIO_ENDPOINT_URL // Endpoint URL you configured in the sandbox, used for validation
};

const whatsAppAdapter = new TwilioWhatsAppAdapter(
    twilioWhatsAppAdapterSettings,
    adapterSettings);

// Catch-all for errors.
const onTurnErrorHandler = async (context, error) => {
    // This check writes out errors to console log .vs. app insights.
    // NOTE: In production environment, you should consider logging this to Azure
    //       application insights.
    console.error(`\n [onTurnError] unhandled error: ${ error }`);

    // Send a trace activity, which will be displayed in Bot Framework Emulator
    await context.sendTraceActivity(
        'OnTurnError Trace',
        `${ error }`,
        'https://www.botframework.com/schemas/error',
        'TurnError'
    );

    // Send a message to the user
    await context.sendActivity('The bot encountered an error or bug.');
    await context.sendActivity('To continue to run this bot, please fix the bot source code.');
};

// Set the onTurnError for the singleton BotFrameworkAdapter.
adapter.onTurnError = onTurnErrorHandler;

// Create the main dialog.
const myBot = new EchoBot();

// Listen for incoming requests.
server.post('/api/messages', (req, res) => {
    adapter.processActivity(req, res, async (context) => {
        // Route to main dialog.
        await myBot.run(context);
    });
});

server.post('/api/whatsapp/messages', (req, res) => {
    console.log('req', req);
    whatsAppAdapter.processActivity(req, res, async (context) => {
        console.log('context', context);

        // Route to main dialog.
        await myBot.run(context);
    });
});

// Listen for Upgrade requests for Streaming.
server.on('upgrade', (req, socket, head) => {
    // Create an adapter scoped to this WebSocket connection to allow storing session data.
    const streamingAdapter = new BotFrameworkAdapter({
        appId: process.env.MicrosoftAppId,
        appPassword: process.env.MicrosoftAppPassword
    });
    // Set onTurnError for the BotFrameworkAdapter created for each connection.
    streamingAdapter.onTurnError = onTurnErrorHandler;

    streamingAdapter.useWebSocket(req, socket, head, async (context) => {
        // After connecting via WebSocket, run this logic for every request sent over
        // the WebSocket connection.
        await myBot.run(context);
    });
});
```

Here is our configuration for BotFrameworkAdapterSettings:
```
TWILIO_NUMBER=+13396007034
TWILIO_ACCOUNT_SID=HIDDEN
TWILIO_AUTH_TOKEN=HIDDEN
TWILIO_ENDPOINT_URL=https://twilio-second-try.azurewebsites.net/api/whatsapp/messages
```

Here is the configuration in Twilio dashboard:
![image](https://user-images.githubusercontent.com/55238907/83622229-f6ef3680-a58f-11ea-9575-62a8f2c374b7.png)

Here is the configuration in Twilio Whatsapp dashboard:
![image](https://user-images.githubusercontent.com/55238907/83627872-e773eb80-a597-11ea-8710-5f608249f644.png)

Here is the error we are getting in Twilio Debugger dashboard:
![image](https://user-images.githubusercontent.com/55238907/83627754-babfd400-a597-11ea-948a-52af3570745d.png)

Could you please let me know if I am missing something in my configuration / implementation ? Thanks.

**Comment by iMicknl** [comment]
I will have a look to see if I can reproduce this error. Could you share your `package.json` here? I would like to understand which versions and dependencies you have.

**Comment by nboussarsaracn** [comment]
```
{
"name": "echobot",
"version": "1.0.0",
"description": "Bot Builder v4 echo bot sample",
"author": "Microsoft",
"license": "MIT",
"main": "index.js",
"scripts": {
"start": "node ./index.js",
"watch": "nodemon ./index.js",
"lint": "eslint .",
"test": "echo \"Error: no test specified\" && exit 1"
},
"repository": {
"type": "git",
"url": "https://github.com"
},
"dependencies": {
"@botbuildercommunity/adapter-twilio-whatsapp": "^1.2.0",
"botbuilder": "^4.8.0",
"dotenv": "^8.2.0",
"restify": "~8.4.0"
},
"devDependencies": {
"eslint": "^6.6.0",
"eslint-config-standard": "^14.1.0",
"eslint-plugin-import": "^2.18.2",
"eslint-plugin-node": "^10.0.0",
"eslint-plugin-promise": "^4.2.1",
"eslint-plugin-standard": "^4.0.1",
"nodemon": "~1.19.4"
}
}
```

**Comment by iMicknl** [comment]
I just tried your code and it works like a charm here. `502 Bad Gateway` is most of the time an issue with the deployment, have you verified if you can post to your endpoint? Could you try accessing it again via Twilio?

<img width="648" alt="Screenshot 2020-06-03 at 12 53 59" src="https://user-images.githubusercontent.com/1424596/83628784-54d44c00-a599-11ea-8a10-770734346055.png">

**Comment by nboussarsaracn** [comment]
Thanks for the update @iMicknl.

In Azure Portal, I have defined one resource group called 'twilio-second-try'.

The resource group has a Web App Bot service called 'twilio-second-try' too and its associated Service Plan called 'twilio-second-try' too.
![image](https://user-images.githubusercontent.com/55238907/83629935-471fc600-a59b-11ea-96a3-9afa6ed9ff16.png)

Here is the channel configuration of the Web App Bot. As you can see, I did not enable Twilio (SMS) as it is not mentioned in the Twilio WhatsApp Adapter documentation.
![image](https://user-images.githubusercontent.com/55238907/83630092-864e1700-a59b-11ea-9c5a-426ba27bd4c6.png)

I have the Web Chat channel enabled and I can interact with the bot via this channel. As you can see nelow, it does not seem to be a deployment issue. 
![image](https://user-images.githubusercontent.com/55238907/83630263-d331ed80-a59b-11ea-9453-5006d2ad0310.png)

Hence, using Postman, I am not able to get proper response by doing a `POST` to `https://twilio-second-try.azurewebsites.net/api/messages` (am I doing something wrong? Maybe I shouldn't call this url but another endpoint). I am getting an `HTTP 500 Internal Server Error` because of an Authentication failure caused by `botframework-connector/MicrosoftAppCredentials` not receiving correct settings (i.e. `appId` & `appPassword`) from `adapterSettings.
Note: I followed this [documentation](https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-connector-authentication?view=azure-bot-service-4.0) for Authentication.
[image](https://user-images.githubusercontent.com/55238907/83633246-ea270e80-a5a0-11ea-8708-122cfa0f94f4.png)

As for the `POST` to `https://twilio-second-try.azurewebsites.net/api/whatsapp/messages`, I am always getting `HTTP 401 Unauthorized` even with the Bearer Token put in the Authorization request header:
![image](https://user-images.githubusercontent.com/55238907/83633756-bdbfc200-a5a1-11ea-8685-f781ce45c7fb.png)

What are your thougts?

**Comment by iMicknl** [comment]
Have you tried linking `twilio-second-try` to Twilio? Looking at your endpoint, this deploy went well and should be working. 

The `HTTP 500 Internal Server Error` is not related to an authentication error, but sounds like an issue with the deployment / dependencies.

**Comment by nboussarsaracn** [comment]
Do you mean creating a Twilio (SMS) channel in the Web App Bot?

The `HTTP 500 Internal Server Error` is thrown because the `appId` and `appPassword` parameters are not correctly set in the class `MicrosoftAppCredentials` which is part of the `botframework-connector` library. Please note that this error is only thrown when I use POSTMAN, using the `Web Chat` channel or the `Bot Framework Emulator` works fine.

You are referring to a deployment / dependencies issue. It can't be dependencies because you just confirmed that the same project dependencies work fine for you (in the example you added above). Let's say it is a deployment issue, how do you explain that the bot is reachable via the `Web Chat` channel?

**Comment by nboussarsaracn** [comment]
What are your channels configuration in Web App Bot? Also, do you have any specific configuration in your App Service or Web App Bot?

**Comment by nboussarsaracn** [comment]
By the way, a [similar issue](https://stackoverflow.com/questions/61671876/twillio-whatsapp-adapter-microsoft-botframework) is still open in stackoverflow

**Comment by iMicknl** [comment]
> Do you mean creating a Twilio (SMS) channel in the Web App Bot?

No, you don't need any additional channel in Azure Web Chat since you are using a custom adapter which will bypass the Azure Bot Service.

> The `HTTP 500 Internal Server Error` is thrown because the `appId` and `appPassword` parameters are not correctly set in the class `MicrosoftAppCredentials` which is part of the `botframework-connector` library. Please note that this error is only thrown when I use POSTMAN, using the `Web Chat` channel or the `Bot Framework Emulator` works fine.

The Web Chat channel doesn't go through the `/api/whatsapp/messages` endpoint, but communicates with the `/api/messages` endpoint. Nevertheless should this not make that much of a difference. I will investigate.

> You are referring to a deployment / dependencies issue. It can't be dependencies because you just confirmed that the same project dependencies work fine for you (in the example you added above). Let's say it is a deployment issue, how do you explain that the bot is reachable via the `Web Chat` channel?

What I meant with the deployment / dependencies, is that a required node_module could be missing at your web app. However, if the Web Chat channel is working, that should indeed not be the problem in your example.

I will investigate and deploy this example on Azure myself. My test this morning was using my local copy and ngrok.

**Comment by nboussarsaracn** [comment]
Thanks for your support @iMicknl.

I would also be glad if you share with me your ngrok settings to be able to run WhatsApp Adapter locally ;)

**Comment by nboussarsaracn** [comment]
Hi @iMicknl, I hope you are progressing well! Please let me know if I can help.

**Comment by nboussarsaracn** [comment]
Hi @iMicknl, have you got any update regarding that topic?

**Comment by iMicknl** [comment]
I will give it a try @nboussarsaracn. Are you running this package on App Service for Windows or Linux? Did you had a look at your application log after you faced those errors.

**Comment by nboussarsaracn** [comment]
Hi @iMicknl,

Thanks for the reply.

Well, I think we are not using the same setup in Azure. Please find below the services I am running for this use case:
![image](https://user-images.githubusercontent.com/55238907/84641102-e2e5f600-aefa-11ea-8a5a-586e66422e70.png)

As you can see, I am using a `Web App Bot` with an `App Service`. I did not use a Code First approach, I rather created the whole resource group and the Web App Bot via Azure console. Therefore, I am not sure if this is Azure App Service for Linux or for Windows - I am not even sure if this applies as we are not deploying to a regular `Web App` but to a `Web App Bot`.

Regarding the `WEBSITE_NODE_DEFAULT_VERSION`, I have it set to the correct version, please see the screenshot below. This is not a dependency problem as I have the bot running properly using the `Web Chat` channel and the `npm install` never fails.
![image](https://user-images.githubusercontent.com/55238907/84641249-0dd04a00-aefb-11ea-9cdd-8e24bcf6122c.png)

I made changes to the existing resource group and now I have the solution running with WhatsApp working using `Directline` channel. I am still curious about how to make it work with the adapter you created. For that, I created a new resource group to debug with you your adapter.

Here is the resource group:
![image](https://user-images.githubusercontent.com/55238907/84648746-bd121e80-af05-11ea-8994-76e54c8267a7.png)

Here are the `TwilioWhatsAppAdapter` settings:
![image](https://user-images.githubusercontent.com/55238907/84649996-c1d7d200-af07-11ea-9d72-754f2f310a27.png)

A question crosses my mind, regarding the parameter `phoneNumber` of the `TwilioWhatsAppAdapter` settings, you mentioned in the documentation that `The From parameter consisting of whatsapp: followed by the sending WhatsApp number (using E.164 formatting)`, how I understand this sentence is that I need to tell the adapter which phone number is going to send messages to it, right? In this case, what if you want multiple numbers talking to your bot?

Now, after setting up everything again, with the settings mentioned above, the request from Twilio now reaches the server as I can see the console log of the `req.body` which is evaluated to `undefined` and the following error:
`(node:28600) UnhandledPromiseRejectionWarning: Error: TwilioWhatsAppAdapter.sendActivities(): Twilio could not find a Channel with the specified From address.at TwilioWhatsAppAdapter.<anonymous> (D:\home\site\wwwroot\node_modules\@botbuildercommunity\adapter-twilio-whatsapp\lib\twilioWhatsAppAdapter.js:86:35)at Generator.throw (<anonymous>)at rejected (D:\home\site\wwwroot\node_modules\@botbuildercommunity\adapter-twilio-whatsapp\lib\twilioWhatsAppAdapter.js:6:65)at process._tickCallback (internal/process/next_tick.js:68:7)`

Last but not least, I do not have a `logging-errors.txt` file in Kudu -> Debug Console -> CMD. Please see the screenshot below. I actually see the logs in App Service ->  Monitoring -> Log Stream.
![image](https://user-images.githubusercontent.com/55238907/84651832-d9648a00-af0a-11ea-9262-406df13e1e80.png)

**Comment by iMicknl** [comment]
> A question crosses my mind, regarding the parameter `phoneNumber` of the `TwilioWhatsAppAdapter` settings, you mentioned in the documentation that `The From parameter consisting of whatsapp: followed by the sending WhatsApp number (using E.164 formatting)`, how I understand this sentence is that I need to tell the adapter which phone number is going to send messages to it, right? In this case, what if you want multiple numbers talking to your bot?

This is not correct. This should be the WhatsApp enabled phone number, provided by Twilio. Your error below is related to the fact that you are not using the right number. The `phoneNumber` paramater is expecting to have the number where the bot will reply from. 

```
wilioWhatsAppAdapter.sendActivities(): Twilio could not find a Channel with the specified From address.at TwilioWhatsAppAdapter.
```

I will have a look if we can make those instructions more clear in a future version.

**Comment by nboussarsaracn** [comment]
Hi @iMicknl, I changed it to the Whatsapp Number provided by Twilio and now it works like charm :) Thank you for the support!

**Comment by iMicknl** [comment]
@nboussarsaracn great to hear! And by now, you should also have improved your debugging experience on Azure App Service a little bit. In the Application folder with different logfiles, you should also be able to find some of the errors you experienced before.
